export const RU = {
    OK: "ОК",
    SteelMill: "Сталелитейный завод",
    StainlessSteelPlant: "Завод нержавеющей стали",
    CircuitFoundry: "Цех литейных электросхем",
    IntegratedCircuit: "Интегральная микросхема",
    OilWell: "Нефтяная скважина",
    Wood: "Дерево",
    LoggingCamp: "Лесоповал",
    LumberMill: "Лесопилка",
    Lumber: "Пиломатериал",
    Paper: "Бумага",
    PaperMill: "Бумажная фабрика",
    Book: "Книга",
    BookPublisher: "книжное издательство",
    OilRefinery: "Нефтеперерабатывающий завод",
    Sell: "Продать",
    Upgrade: "Улучшить",
    Build: "Построить",
    Inspect: "Проверить",
    Buildings: "Здания",
    Iron: "Железо",
    Actions: "Действия",
    FuelType: "Выберите топливо",
    FuelCost: "Стоимость топлива",
    FuelConsumption: "%{fuel} Потребление",
    FuelEconomy: "Экономия топлива",
    FuelProduction: "%{fuel} Производство",
    FuelInStorage: "%{fuel} . ",
    Plastic: "Пластик",
    FuelSurplus: "%{fuel} Избыток",
    Petrol: "Бензин",
    Buy: "Купить",
    NoLiquidity: "Отсутствие Ликвидности",
    NoLiquidityTurnOffAutoSell: "На рынке не хватает ликвидности для %{res}, автопродажа отключена",
    Multiplier: "Множитель",
    MultiplierDesc: "Каждые 10 уровней, вы получаете +1 множитель",
    SellBuilding: "Продать Здание",
    PowerGrid: "Энергосистема",
    TradeAmount: "Сумма сделки",
    SortBy: "Сортировать по",
    SortByPrice: "Цена",
    SortByAmount: "Сумма",
    NotEnoughResourcesForTrade: "Недостаточно ресурсов в Торговом центре для этой торговли",
    NotEnoughResources: "Недостаточно ресурсов для этой операции",
    Transportation: "Перевозка",
    Cash: "Деньги",
    Aluminum: "Алюминий",
    ResearchPoint: "Очки Науки",
    Unlock: "Разблокировка",
    BuildingUnlocked: "%{building} был разблокирован",
    Science: "Наука",
    ScienceFromPowerDesc: "Электростанции производят небольшое количество науки при производстве электроэнергии",
    Culture: "Культура",
    School: "Школа",
    University: "Университет",
    Polytechnic: "Политехнический",
    Colosseum: "Колизей",
    WindTurbine: "Ветряная турбина",
    Engine: "Двигатель",
    EngineFactory: "Завод двигателей",
    CameraFactory: "Фабрика камер",
    Camera: "Камера",
    Gun: "Оружие",
    GunFactory: "Оружейный завод",
    Aircraft: "Самолет",
    AircraftFactory: "Авиационный завод",
    Zeppelin: "Цеппелин",
    ZeppelinFactory: "Завод цеппелинов",
    Tank: "Танк",
    TankFactory: "Танковый завод",
    MinimumTradingAmount: "Вы не можете торговать ниже минимальной суммы",
    CoalPowerPlant: "Угольная электростанция",
    PetrolPowerPlant: "Бензиновая Силовая Установка",
    Copper: "Медь",
    Gas: "Природный газ",
    GasPump: "Насос для природного Газа",
    GasPowerPlant: "Газовая электростанция",
    Missile: "Cнаряд",
    MissileFactory: "завод Снаряд",
    Rocket: "Ракета",
    RocketFactory: "Завод Ракет",
    BuildingPermit: "Разрешение на строительство",
    BuildingPermitDesc:
        "У вас есть разрешение на %{amount} здания, вы уже построили %{amountBuilt} у вас осталось %{amountLeft}",
    BuildingLocked: "Здание еще не доступно, вам нужно сначала разблокировать его в научной лаборатории",
    BuildQueue: "Очередь сборки",
    BuildQueueDesc: "Количество зданий, стоящих в очереди в настоящее время",
    MaxBuilders: "Максимум Строителей",
    MaxBuildersDesc: "Количество зданий, которые вы можете построить одновременно",
    Silicon: "Кремний",
    AluminumMine: "Алюминиевый рудник",
    CopperMine: "Медный рудник",
    SiliconMine: "Кремниевая шахта",
    IronMine: "Железный рудник",
    CoalMine: "Угольная шахта",
    Headquarter: "Штаб-квартира",
    ResearchLab: "научная лаборатория",
    TradeCenter: "Торговый Центр",
    Resources: "Ресурсы",
    NotEnoughPower: "💡 Недостаточно мощности, подумайте об увеличении мощности питания",
    NotEnoughFuel: "Not enough %{fuel} for this operation",
    NotEnoughCash: "Не хватает наличных для этой операции",
    NotEnoughSwissMoney: "Not enough Swiss money for this operation",
    BuildingNotEnoughFuel: "💡 Недостаточно %{fuel}",
    AutoSell: "АвтоПродажа",
    SellAll: "Продать все",
    Change: "Изменить",
    StatisticsBureau: "Статистическое бюро",
    LogisticsDepartment: "Logistics Department",
    From: "From",
    Top20FuelCost: "Топ-20 Затрат На Топливо",
    To: "To",
    TransportTime: "Transport Time",
    TopN: "Топ %{n}",
    Warehouse: "Склад",
    TradeWarehouse: "Грузовой Склад",
    Coal: "Уголь",
    Video: "Видео",
    ClothingFactory: "Швейная фабрика",
    Clothes: "Одежда",
    Fashion: "Мода",
    FashionFactory: "Фабрика моды",
    VideoFarm: "Видео Ферма",
    SantaFactory: "Фабрика Санты",
    Santa: "Санта",
    Car: "Машина",
    CarFactory: "Автомобильный завод",
    Ship: "Корабль",
    SolarPanel: "Солнечная Панель",
    SolarPanelDesc: "💡 Солнечные панели работают только 5 секунд из каждых 10 секунд - все циклы равны",
    WindTurbineDesc: "💡 Ветряные турбины работают только 8 секунд из каждых 10 секунд - циклы не равны",
    Movie: "Кино",
    MovieStudio: "Киностудия",
    Sitcom: "Ситком",
    TVStudio: "ТВ Студия",
    PC: "ПК",
    GameStudio: "Игровая студия",
    Game: "Игра",
    ComputerFactory: "Компьютерная фабрика",
    Shipyard: "Верфь",
    PowerUsage: "Энергопотребление",
    PowerSupply: "источник питания",
    PowerSurplus: "Избыток энергии",
    Level: "Уровень",
    Power: "Мощь",
    CentralBank: "Центральный банк",
    ResourceInput: "В",
    ResourceOutput: "Из",
    ResourceStorage: "Место хранения",
    ResourceChange: "Изменить",
    ResourceInOutDesc: "💡 Нажмите на цифры Из-В выше, чтобы выделить соответствующие выходные и входные здания",
    ResourceChart: "Диаграмма ресурсов",
    MarketUpdateIn: "Следующее обновление рыночной цены через %{time}",
    Income: "Доход",
    Semiconductor: "Полупроводник",
    SemiconductorFactory: "Полупроводниковый завод",
    SemiconductorFab: "Полупроводниковая фабрика",
    Steel: "Сталь",
    Bitcoin: "Биткоин",
    BitcoinFarm: "Биткойн-ферма",
    Dogecoin: "Догикоин",
    DogecoinFarm: "Догикоин ферма",
    Guitar: "Гитара",
    GuitarFactory: "Фабрика Гитар",
    Drum: "Барабан",
    DrumFactory: "Барабанная фабрика",
    RecordingStudio: "Студия звукозаписи",
    OperaHouse: "Оперный театр",
    CoalGasificationPlant: "Завод угольная газификация",
    GasProcessingPlant: "Газоперерабатывающий завод",
    Music: "Музыка",
    Glass: "Стекло",
    PhoneFactory: "Телефонная фабрика",
    Phone: "Телефон",
    GlassFactory: "Стекольный завод",
    Oil: "Нефть",
    Chromium: "Хром",
    ChromiumMine: "Хромовый рудник",
    Uranium: "Уран",
    EnrichedUranium: "Обогащенный уран",
    NuclearPowerPlant: "Атомная электростанция",
    UraniumEnrichmentPlant: "Завод по обогащению урана",
    UraniumMine: "Uranium Mine",
    Titanium: "Титан",
    TitaniumMine: "Титановый рудник",
    TitaniumAlloyPlant: "Завод титановых сплавов",
    ChromiumAlloyPlant: "Завод хромовых сплавов",
    Input: "Ввод",
    PanelPosition: "Положение панели",
    PanelPositionDesc: "Показать боковую панель слева, справа или автоматически",
    InputCapacity: "Входная Емкость",
    InputCapacityPerCycle: "Входная Мощность / Цикл",
    Output: "Выход",
    OutputCapacity: "Выходная мощность",
    OutputCapacityPerCycle: "Выходная мощность / Цикл",
    ResourceDeposit: "Депозит Ресурсов",
    RecommendedBuilding: "💡 This tile has %{resource} deposit",
    AdjacentBonus: "Граничащий Бонус",
    AdjacentBonusDesc: "Вы получаете %{bonus}% дополнительной мощности для каждого соседнего рабочего здания того же типа",
    ConsiderIncreaseProduction: "💡 Рассмотрим увеличение производства %{resource}",
    AlwaysTransportInput: "Режим накопления запасов",
    AlwaysTransportInputTradeCenter: "Всегда Экспортируйте",
    AlwaysTransportInputTradeCenterDesc:
        "Всегда транспортируйте ресурсы в Торговый центр, даже если автоматическая продажа для этого ресурса не включена",
    AlwaysTransportInputDesc: "Всегда транспортируйте входные ресурсы, даже если они превышают минимальные производственные потребности",
    ProductionCycleLength: "Производственный Цикл",
    ProductionCycleLengthDesc:
        "Продолжительность одного производственного цикла измеряется в секундах. Удлинение цикла соответственно увеличит ввод/вывод за цикл и тем самым снизит его приоритет при извлечении входных ресурсов",
    MaxInputDistance: "Максимальное Входное Расстояние",
    MaxInputDistanceDesc:
        "Максимальное расстояние, с которого это здание может извлекать входные ресурсы, измеряется в количестве плиток",
    AutoSellCapacity: "Емкость автоматической продажи",
    AutoSellCapacityDesc: "Максимальное количество ресурсов, которые автопродажа может обрабатывать в секунду, на каждый ресурс",
    CurrentAutoSellCapacityMultiplier: "Текущий множитель: x%{n}",
    AutoSellConcurrency: "АвтоПродажа",
    AutoSellConcurrencyDesc: "Максимальное количество ресурсов автопродажа может обрабатывать одновременно",
    MaxAutoSellConcurrencyReached:
        "You have reached maximum auto sell concurrency, turn off another auto sell to enable this one",
    CannotSellBuilding: "Cannot sell building at this time",
    WallStreet: "Уолл-стрит",
    MarketCap: "Рыночная капитализация",
    MarketCapDesc: "Общая рыночная капитализация (т. е. рыночная стоимость) вашей корпорации",
    BuildingValuation: "Оценка стоимости Здания",
    BuildingValuationDesc: "Общая стоимость ваших зданий, включая разрешения на строительство и улучшения",
    ResourcesValuation: "Оценка Ресурсов",
    ResourcesValuationDesc: "Общая стоимость ресурсов в вашем инвентаре",
    Battery: "Батарея",
    BatteryFactory: "фабрика батарей",
    RatingBuy: "купить",
    RatingSell: "продать",
    SwissShop: "Швейцарский магазин",
    RatingHold: "Держать",
    RatingOutperform: "Outperform",
    RatingUnderperform: "Underperform",
    StockRating: "Stock Rating",
    JetEngine: "Jet Engine",
    Helicopter: "Helicopter",
    Lithium: "Lithium",
    LithiumMine: "Lithium Mine",
    LiionBatteryFactory: "Li-ion Battery Factory",
    HelicopterFactory: "Helicopter Factory",
    Satellite: "Satellite",
    ToyFactory: "Toy Factory",
    Toy: "Toy",
    SpaceStation: "Space Station",
    SpaceStationFactory: "Space Station Factory",
    OperatingSystem: "Operating System",
    OperatingSystemCompany: "Operating System Inc",
    LinuxDistribution: "Linux Distribution",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Console",
    ConsoleFactory: "Console Factory",
    Train: "Train",
    TrainFactory: "Train Factory",
    ShoeFactory: "Shoe Factory",
    Shoes: "Shoes",
    ArtilleryFactory: "Artillery Factory",
    Artillery: "Artillery",
    SubmarineFactory: "Submarine Factory",
    Submarine: "Submarine",
    Spaceship: "Spaceship",
    RobotFactory: "Robot Factory",
    Robot: "Robot",
    SpaceshipFactory: "Spaceship Factory",
    SatelliteFactory: "Satellite Factory",
    JetEngineFactory: "Jet Engine Factory",
    StockRatingDesc:
        "Stock rating consensus from Wall Street analysts, which affects your market cap and is updated together with the market",
    InterestRate: "Overnight Interest Rate",
    InterestRateDesc: "Interest you earn on your market capitalization while you are offline",
    OfflineEarning: "Offline Earning",
    OfflineEarningDesc: "Offline Earning depends on your market cap and interest rate",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline Earning Time",
    OfflineEarningTimeDesc: "You will earn offline earning for up to this threshold",
    BuyPermit: "Buy Permit",
    NotEnoughBuildingPermit: "Not enough building permits. Please buy more to build new buildings",
    MovingAverage: "Moving Average",
    MovingAverageDesc: "Show moving average of change of resources instead of real-time change",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Turn on zoom support. Use your mouse wheel to zoom. Current zoom is %{zoom}",
    AllowZoomMobileDesc: "Turn on zoom support. You can pinch to zoom. Current zoom is %{zoom}",
    Settings: "Settings",
    SellBuildingDesc:
        "Selling a building will refund you 50% of your investment and 50% of the resources will be transported to Trade Center",
    SellBuildingFullRefundDesc:
        "Building Recycle policy is active, selling a building will give you full refund until in %{time}",
    Sound: "Sound Effect",
    SoundDesc: "Turn on sound effect like click or error sound",
    AutoHighlight: "Auto Highlight",
    AutoHighlightDesc: "Automatically highlight buildings of the same type when you select a building",
    MusicDesc: "Turn on music: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Icons",
    MisplacedBuilding: "⛔ This %{building} is not placed on top of the correct resource deposit",
    UnderConstruction: "%{building} is under construction",
    Left: "Слева",
    Right: "Справа",
    Auto: "Автоматически",
    HighlightBuildings: "Highlight Buildings",
    HighlightTurnedOff: "...that are shut down",
    HighlightStockpileModeOn: "...that have stockpile mode on",
    HighlightWarehouseOnly: "...that are only for warehouses",
    HighlightProductionCycleNotDefault: "...that have production cycle > 1",
    HighlightMaxInputDistanceNotDefault: "...that have max input distance < ∞",
    HighlightNotMakingProfit: "...do not make a profit",
    NBuildingsAreHighlighted: "%{n} building(s) are highlighted",
    OnlyToWarehouse: "Only for Warehouses",
    OnlyToWarehouseDesc: "Only warehouses can transport resources from this building",
    TurnOffProduction: "Выключить",
    TurnOffProductionDesc:
        "Turn off the building's production. The building will no longer transport resources and use power",
    ApplyToAll: "Apply To All %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Безлимит",
    Transport: "Транспорт",
    TileModifier: "Tile Modifier",
    ShowAllModifiers: "Показать все Модификаторы",
    HideAllModifiers: "Скрыть Все Модификаторы",
    NumberOfBuildings: "Количество зданий, которые у вас есть",
    ShowContent: "Показать содержимое",
    HideContent: "Скрыть содержимое",
    BuyExpansionPack: "Buy For %{price}",
    Cities: "Города",
    WarehouseInputCapacityDesc: "Amount of resources the warehouse can transport inward per second, per resource.",
    WarehouseBuildDesc: "Warehouses can transport and store any resources",
    InputStrategy: "Input Strategy",
    InputStrategyClose: "Closer",
    InputStrategyCloseDesc: "Prefer the closest warehouse which has enough resources",
    InputStrategyFar: "Farther",
    InputStrategyFarDesc: "Prefer the farthest warehouse which has enough resources",
    InputStrategyAmount: "Amount",
    InputStrategyAmountDesc: "Prefer the warehouse with the largest amount of the resources, regardless of distance",
    FuelCostSave: "Fuel Cost Save",
    FuelCostSaveDesc:
        "Warehouses save a certain percentage of fuel for transporting resources inward compared to other buildings, the higher the level, the more the save",
    SoftwareCompany: "Software Company",
    Software: "Software",
    ScreenFactory: "Фабрика экранов",
    Screen: "Экран",
    JoinDiscord: "Присоединяйтесь к нашему Discord серверу для получения последних обновлений, советов и обсуждений",
    ClaimOfflineEarning: "Claim Offline Earning",
    OfflineTime: "Оффлайн время",
    Minutes: "%{time}мин",
    MaxUpgrade: "Максимальное улучшение",
    MaxUpgradeDesc: "Вы достигли максимального улучшения",
    ClaimAmount: "Деньги +%{amount}",
    EarningPerMinute: "Заработок",
    EffectiveTime: "Эффективное Время",
    EffectiveTimeDesc: "Ваше эффективное автономное время заработка ограничено %{time}min",
    BuildSearchPlaceholder: "Введите здание или ресурс для поиска",
    MineOverlayWarning: "%{building} is not affected by tile modifier",
    WholesaleCenter: "Оптовый Центр",
    OrderFrom: "Order from %{name}",
    ExpireIn: "Expire In",
    ProfitMargin: "Размер прибыли",
    NotMakingProfitWarning: "💡 Production not profitable, consider shut it down",
    TurnOnAllProductions: "Production On",
    TurnOnAllProductionsDesc: "Turn on productions of all buildings, cannot be used when Cost Saver policy is active",
    OperationSuccessful: "This operation has been successfully completed",
    TurnOn: "Turn On",
    Reward: "Reward",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cycle",
    PolicyPoint: "Policy Point",
    PolicyPointPerMinute: "Generate Rate",
    PolicyPointPerMinuteDesc: "You acquire policy points every minute in the game",
    YourWilLGaimPolicyPoints: "You will gain %{amount} policy points in %{time}s",
    PolicyPointDesc: "💡 The more active policies, the more cost for each policy",
    NextOrderIn: "Next Order In",
    FillOrder: "Fill Order",
    RejectOrder: "Pass",
    YouHave: "You have %{amount}",
    WholesaleCenterLocked:
        "You need at least %{required} different resources to unlock Wholesale Center. You only have %{current} resources",
    OrderFilled: "The order from %{from} has been successfully filled!",
    PolicyCenter: "Policy Center",
    NewOrder: "A new order from %{from} has arrived, please check in Wholesale Center",
    Policies: "Policies",
    PolicyNotEnoughTime: "You don't have enough policy points for this policy",
    TimeLeft: "%{time} Left",
    WholesaleCenterOrderFaster: "World's Fair",
    WholesaleCenterOrderFasterDesc: "Wholesale Center receives orders 2x faster and the order size is 2x bigger",
    PolicyOilWellPowerx2: "Supercharge Oil Well",
    PolicyOilWellPowerx2Desc: "Oil wells produce 2x oil and use 2x power",
    HalfTransportSpeed: "Slow Down To Save Up",
    HalfTransportSpeedDesc: "Transportation speed is slowed down by 25% and fuel cost is reduced by 25%",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "Oil Refineries produce 50% more petrol and 50% less plastic",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Buildings will prefer to transport from previous source, instead of searching for the best source every cycle (FREE POLICY)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "Oil Refineries produce 50% less petrol and 50% more plastic",
    FreeOilTransport: "Free Oil Transport",
    FreeOilTransportDesc: "Oil transport doesn't cost fuel but oil wells use 2x power",
    SuperSteelMill: "Hearts of Iron",
    SuperSteelMillDesc: "Steel mills use 50% less coal and 25% more iron and 25% more power",
    AlSemiconductor: "Al Circuit",
    AlSemiconductorDesc: "Circuit foundries use aluminum instead of copper",
    CostSaver: "Cost Saver",
    CostSaverDesc: "If a building's input cost more than its output, shut down the production",
    CostSaverBuildingDesc:
        "Cost Saver policy is active, production will turn on/off automatically based on its profitability",
    CostSaverBuildingWarning: "Cost Saver policy is active, you cannot manually change production",
    GlassUseCoal: "Black Glass",
    GlassUseCoalDesc: "Glass factories use 50% more coal and 50% less silicon",
    AdjacentBonusOnlyOutput: "Adjacent Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Adjacent bonus does not require more input but uses more power and is only 50% effective",
    IronMine2xOutput: "Heavy Iron",
    IronMine2xOutputDesc: "Iron mines produce 2x iron but iron transport costs 2x fuel",
    SolarPanelAlwaysWork: "The Sun Never Sets",
    SolarPanelAlwaysWorkDesc: "Solar panel works 100% of the time but produces 60% less power",
    SteelScience: "Knowledge Through Steel",
    SteelScienceDesc: "Steel mills use 2x input and produce extra science",
    ShowWarehouse: "Unlock Warehouse",
    ShowWarehouseDesc:
        "A warehouse is a special building that only transports and store resources and can provide fuel save (FREE POLICY)",
    WholesaleCenterProducingOnly: "Wholesale Partners",
    WholesaleCenterProducingOnlyDesc:
        "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "If a resource's output capacity falls short, buy the shortage amount from Trade Center automatically (If the resource has auto sell on, it will be ignored)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree policy is on, Trade Center will automatically buy resources in shortage",
    ExtraPolicyPoints: "Political Lobbyist",
    ExtraPolicyPointsDesc: "Increase policy point production capacity by 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromium alloy plants do not use Lithium but use 2x Iron instead",
    DoubleTileModifier: "Nature's Power",
    DoubleTileModifierDesc: "All tiles' modifier's effect x2 - both positive and negative",
    TileModifierOutputOnly: "Tile Modifier Plus",
    TileModifierOutputOnlyDesc:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective",
    GasPlantPetrol: "Gas Liquidizer",
    GasPlantPetrolDesc: "Gas power plants use extra gas to produce petrol",
    BuildingRecycle: "Building Recycle",
    BuildingRecycleDesc: "Get full refund when you sell a building within 1 min after construction",
    CoalPlantFuel: "Coal Liquidizer",
    CoalPlantFuelDesc: "Coal power plants use extra coal to produce petrol",
    Welcome: "Добро пожаловать!",
    SeeTutorialAgain: "Повторить обучение",
    ReadSteamGuide: "Официальное руководство по Steam",
    HelpTranslateTheGame: "Помогите перевести игру",
    SkipTutorial: "Пропустить обучение",
    NextTutorial: "Следующий",
    Tutorial1:
        "Industry Idle - это игра по <em>управлению ресурсами</em> игра, в которой вы строите заводы🏭, производить товары📦 и зарабатываете деньги💸.<br><br>Давайте пройдемся по некоторым основным понятиям(базарим по понятиям), чтобы вы начали - это не займет много времени, я обещаю.",
    Tutorial2:
        "Все здания нуждаются в электроэнергии⚡, у тебя есть <em>ветряная турбина</em> которая создает энергию. Вы можете увидеть свой текущий источник питания в левой части верхней панели.<br><br>Вы, наверное, заметили, что ветрянные турбины работают только <em>80%</em> времени. Вы можете рассмотреть возможность строительства других типов электростанций, которые генерируют стабильную энергию.",
    Tutorial3:
        "У тебя много <em>залежей ресурсов</em> на карте. Чтобы добывать ресурсы, вы должны строить шахты⛏️ <em>на вершине</em> соответствующего депозита.<br><br>Например, у вас есть <em>нефтяная скважина🛢️</em> что извлекает <em>нефть</em> из нефтяного месторождения.<br></br>Запасы ресурсов неограниченны - не нужно беспокоиться о том, что они закончатся. Помимо шахт, на любой пустой плитке можно строить и другие здания.",
    Tutorial4:
        "Затраты на транспортировку ресурсов топливо. На этой карте вы можете использовать <em>бензин⛽</em> в качестве топлива. У вас есть <em>нефтеперерабатывающий завод</em> который транспортирует нефть из нефтяной скважины и производит бензин.<br><br>Крошечное движение <em>точек</em> представляют собой движение ресурсов в реальном времени. Вы должны оптимизировать расположение своих зданий, чтобы минимизировать расстояние перемещения.<br><br><em>Улучшаясь</em>, ваши здания увеличат свою производительность, но также увеличат потребление энергии и потребляемую мощность.<br><br>Вы можете изменить тип топлива в транспортном центре 🚦 . Не забудьте убедиться, что ваше производство топлива выше потребления, иначе ваше производство остановится, когда у вас закончится топливо.",
    Tutorial5:
        "Чтобы заработать деньги, вам нужно экспортировать свои ресурсы через торговый центр. Для этого просто включите  <em>АвтоПродажу</em> для этого ресурса.<br></br>Вы также можете купить ресурсы в торговом центре. Помни, <em>если вы покупаете ресурс, вы поднимаете цену</em> и если вы продадите ресурс, вы снизите цену.<br><br> Рынок <em>летучий</em> и цена 📈 регулярно меняется.",
    Tutorial6:
        "Чтобы строить новые здания, вам нужно сначала разблокировать его в <em>Научной Лаборатории🧪</em>. Исследовательская лаборатория также преобразует науку в Очки Науки.<br><br>Ваша ветряная турбина (и другие электростанции) производит небольшое количество науки при работе. И вы можете построить школу 🏫 и другие специальные здания для дальнейшего развития науки.<br><br>Теперь, когда вы изучили все основы, начинайте строить свою экономику! Дам тебе <em>деньги💸</em> и <em>топливо⛽</em> чтобы дать толчок в развитии.",
    WelcomePlay: "Играть",
    WelcomePlayMuted: "играть (🔇Музыка)",
    Changelog: "Изменения",
    ChangelogGotIt: "Получить",
    Chat: "Чат",
    Send: "Отправить",
    Import: "Импорт",
    Export: "Экспорт",
    SteamCloudBackup: "Резервное копирование Steam Cloud",
    LastBackupAt: "Последняя резервная копия",
    RestoreFromBackup: "Восстановление из резервной копии",
    RestoreFromBackupFail: "Не удалось восстановить резервную копию из Steam Cloud: Чувак, ты уверен, что резервная копия есть?",
    RestoreFromBackupTitle: "Чувак, ты уверен?",
    RestoreFromBackupDesc:
        "Обычно вам не нужно восстанавливать данные из облачной резервной копии, если только ваше локальное сохранение не потеряно. Облачное резервное копирование немного старше вашего локального сохранения",
    ChatMessages: "Сообщения чата",
    ChatPlaceholder: "Введите свое сообщение: максимум 100 символов",
    ChangeName: "Изменить",
    SaveName: "Сохранить",
    NameValidationRule: "Your name should only contain letters and numbers and be between 5-15 chars",
    NameValidationRuleProfanity: "Your name should not contain profanity",
    ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
    NameSaved: "Your name has been changed successfully",
    NoMessages: "No new messages",
    Leaderboard: "Leaderboard",
    LeaderboardDesc: "The leaderboard score is all the Swiss money you've ever earned",
    Name: "Имя",
    Rank: "Ранг",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2:
        "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building is determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Energy Saving",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptOutDesc:
        "This will no longer send leaderboard score. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Наградное видео не завершилось",
    RewardAdsNotAvailable: "Reward video is not available (currently only iOS/Android is supported)",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Highlight "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Out in %{time}",
    FuelRunOutWarning: "💡 Your fuel consumption exceeds production. When fuel runs out, your transportation will halt",
    InAmount: "In: %{number}",
    OutAmount: "Out: %{number}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Expansion Packs",
    ExpansionPack1: "Expansion Pack 1",
    ExpansionPack1Owned: "Expansion Pack 1",
    RequireExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Hide Discord Banner",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Hide Chat Message",
    HideChatDesc: "Hide chat message from the bottom toolbar",
    SortedByDeficit: "Sorted By Deficit",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Swiss Money 💵",
    RestartDesc: "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
    PrestigeGoBack: "Go Back",
    PermanentUpgradeDesc: "This upgrade will carry over if you start in a new city",
    ProductionMultiplier: "Production Multiplier",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    OfflineEarningMultiplier: "Offline Earning Multiplier",
    OfflineEarningMultiplierDesc: "A multiplier that applies to offline earnings",
    PrestigeAlertTitle: "Are you sure?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Cash In",
    Cancel: "Cancel",
    SaveFileCorrupted: "Save File Corrupted",
    CheatDetected: "Your old save did not pass server validation and cannot be read. You will start with a new save",
    LoadGameError: "Failed to Load Game",
    LoadGameErrorMessage: "Error message: %{message}",
    LoadGameErrorDesc: "Please check your Internet connection. If the problem persists, please contact support",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    SaveFileMigrated: "A New Era: Beta Is Here",
    SaveFileMigratedDesc:
        "Thank you for play testing in alpha. Your old map is not compatible but we have migrated your data and give you some bonus",
    ClaimSwissMoney: "Claim %{amount} Swiss Money 💵",
    SaveFileMigratedFinePrint:
        "Your market cap is converted to Swiss Money and your unspent Swiss money is carried forward. You will get 50% bonus Swiss money for play testing in alpha. Max Swiss money that can be carried forward is capped at 200",
    CashIn: "Cash In",
    CurrentCity: "Current City",
    CashInDesc:
        "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
    MoveToNewMap: "Start In A New City",
    CityName: "City",
    CitySize: "Map Size",
    GridType: "Grid Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "City Bonus",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    StockholmBonus:
        "<li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Paper mills are unlocked</li><li>Logging camps have 2x output</li>",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>No tile modifiers</li>",
    Oslo: "Oslo",
    OsloBonus:
        "<li>Oil refineries have 2x capacity</li><li>Gas processing plants have 2x capacity</li><li>Petrol power plants have 2x capacity</li><li>Steel mills use natural gas instead of coal</li><li>Free oil transportation</li>",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Missile factories use enriched uranium instead of titanium and uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories use uranium instead of enriched uranium</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    DetroitBonus:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories do not need batteries</li><li>Train factories have 2x capacity</li>",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>University have 2x productivity</li>",
};
